### ISSUE TITLE
[Suggestion] yoga as a submodule

### ISSUE THREAD

**Issue by Dimous** [darmie/linc_yoga#1]
I noticed it's a good practice to add an externed library as a submodule _(for example: linc_sdl, linc_opengl, linc_openal, linc_ogg and so on)_ You know, to keep dependencies up to date without hassle.

**Comment by darmie** [comment]
Thanks for pointing that out. I'll do that.

**Comment by darmie** [comment]
https://github.com/darmie/linc_yoga/commit/b45b7fd17a820d3adaf79a0aace64d2e939c0699

**Comment by Dimous** [comment]
Hi!
My git client can't clone lib with error "fatal: I don't handle protocol 'git@github.com:https'".
I believe there is a mistake in url parameter. Value can be "git@github.com:facebook/yoga.git" (ssh auth) or "https://github.com/facebook/yoga.git" (no auth).
You can use https://github.com/snowkit/linc_sdl/blob/master/.gitmodules as a reference.

**Comment by darmie** [comment]
Yeah, I will fix that. I had a problem with remote and local repo not being in sync yesterday.
