### ISSUE TITLE
Instantiation with new operator returns a pointer

### ISSUE THREAD

**Issue by Dimous** [darmie/linc_yoga#5]
NewYogaNode and NewYogaNodeWithConfig are returning YGNodeRef and thats ok. 

For example
```c++
namespace config {
YGConfig NewConfig(YGLogger logger) {
return new YGConfig(logger);
}
}
```
new YGConfig returns YGConfig*
I dont know if its meant to be instantiated on the stack or the heap. I'm not sure if I should remove new operator or add *

**Comment by darmie** [comment]
Does it show any errors when you try to build?

**Comment by darmie** [comment]
`new YGConfig()` returns `cpp.Struct<YGConfig>`

**Comment by Dimous** [comment]
I'm talking about:
https://github.com/darmie/linc_yoga/blob/master/linc/linc_yoga.cpp#L23
https://github.com/darmie/linc_yoga/blob/master/linc/linc_yoga.cpp#L29
https://github.com/darmie/linc_yoga/blob/master/linc/linc_yoga.cpp#L35
https://github.com/darmie/linc_yoga/blob/master/linc/linc_yoga.cpp#L41
https://github.com/darmie/linc_yoga/blob/master/linc/linc_yoga.cpp#L44
https://github.com/darmie/linc_yoga/blob/master/linc/linc_yoga.cpp#L50
_Though I'm not an expert in C++, I know that new operator returns pointer._

Probably I was doing something wrong or when using with openfl some different build toolchain is used or it's msvc comipler-specific behaviour, idk.

**Comment by darmie** [comment]
@Dimous ok, now I understand what you mean. 

Using `new` will return a pointer.

**Comment by Dimous** [comment]
linc_yoga needs tests and a build script.

**Comment by darmie** [comment]
I am working on it. Day job hasn't allowed enough time. 

The reason you are seeing some of these issues is because I even tested the library yet.

**Comment by Dimous** [comment]
Cool! I'll wait 😋
